name: fermibottle ci 
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - .clang-format
      - .dockerignore
      - .gitignore
      - docker-compose.yml
      - Dockerfile
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  TEST_TAG: fssc/fermibottle_lite:2026.02.09
  LATEST_TAG: fermi-lat/fermibottle2026:latest

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    # ubuntu-24.04-arm, ubuntu-24.04
    runs-on: ${{ matrix.os }}   
    steps:
      - name: Checkout FermiBottle repository
        uses: actions/checkout@v4
        with:
          path: $GITHUB_WORKSPACE/FermiBottle # Clones to $GITHUB_WORKSPACE/FermiBottle

      - name: Run tests from ScienceTools against FermiBottle
        uses: actions/checkout@v4
        with:
          repository: fermi-lat/ScienceTools # Specify the other repo's name
          path: ScienceTools # Clones to $GITHUB_WORKSPACE/ScienceTools

      # - name: Use Docker in rootless mode.
      #  uses: ScribeMD/rootless-docker@0.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Check inside
        id: confirm_inside_env
        run: |
           echo "look around  jsa"
           pwd
           ls -l

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # with:
        #  buildkitd-flags: --debug

      - name: Build and TEST
        uses: docker/build-push-action@v6
        with:
          context: $GITHUB_WORKSPACE/FermiBottle/docker
          platforms: linux/arm64 
          load: true
          push: true
          tags: ${{ env.TEST_TAG }}
          # file: ./docker/Dockerfile 4,linux/arm64

      - name: Test
        run: |
          docker run ${{ env.TEST_TAG }}
          # docker run --rm ${{ env.TEST_TAG }}

#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          load: true
#          push: false
#          tags: ${{ env.LATEST_TAG }}
